/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as InteractionsRouteImport } from './routes/interactions'
import { Route as LabReportsRouteImport } from './routes/lab-reports'
import { Route as PrescriptionRouteImport } from './routes/prescription'
import { Route as ProfessionalRouteImport } from './routes/professional'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RemindersRouteImport } from './routes/reminders'
import { Route as SafetyRouteImport } from './routes/safety'
import { Route as MedicinesIndexRouteImport } from './routes/medicines.index'
import { Route as MedicinesMedicineIdRouteImport } from './routes/medicines.$medicineId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const InteractionsRoute = InteractionsRouteImport.update({
  id: '/interactions',
  path: '/interactions',
  getParentRoute: () => rootRouteImport,
} as any)
const LabReportsRoute = LabReportsRouteImport.update({
  id: '/lab-reports',
  path: '/lab-reports',
  getParentRoute: () => rootRouteImport,
} as any)
const PrescriptionRoute = PrescriptionRouteImport.update({
  id: '/prescription',
  path: '/prescription',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfessionalRoute = ProfessionalRouteImport.update({
  id: '/professional',
  path: '/professional',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RemindersRoute = RemindersRouteImport.update({
  id: '/reminders',
  path: '/reminders',
  getParentRoute: () => rootRouteImport,
} as any)
const SafetyRoute = SafetyRouteImport.update({
  id: '/safety',
  path: '/safety',
  getParentRoute: () => rootRouteImport,
} as any)
const MedicinesIndexRoute = MedicinesIndexRouteImport.update({
  id: '/medicines/',
  path: '/medicines/',
  getParentRoute: () => rootRouteImport,
} as any)
const MedicinesMedicineIdRoute = MedicinesMedicineIdRouteImport.update({
  id: '/medicines/$medicineId',
  path: '/medicines/$medicineId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/assistant': typeof AssistantRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/interactions': typeof InteractionsRoute
  '/lab-reports': typeof LabReportsRoute
  '/prescription': typeof PrescriptionRoute
  '/professional': typeof ProfessionalRoute
  '/profile': typeof ProfileRoute
  '/reminders': typeof RemindersRoute
  '/safety': typeof SafetyRoute
  '/medicines/$medicineId': typeof MedicinesMedicineIdRoute
  '/medicines/': typeof MedicinesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/assistant': typeof AssistantRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/interactions': typeof InteractionsRoute
  '/lab-reports': typeof LabReportsRoute
  '/prescription': typeof PrescriptionRoute
  '/professional': typeof ProfessionalRoute
  '/profile': typeof ProfileRoute
  '/reminders': typeof RemindersRoute
  '/safety': typeof SafetyRoute
  '/medicines/$medicineId': typeof MedicinesMedicineIdRoute
  '/medicines': typeof MedicinesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/assistant': typeof AssistantRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/interactions': typeof InteractionsRoute
  '/lab-reports': typeof LabReportsRoute
  '/prescription': typeof PrescriptionRoute
  '/professional': typeof ProfessionalRoute
  '/profile': typeof ProfileRoute
  '/reminders': typeof RemindersRoute
  '/safety': typeof SafetyRoute
  '/medicines/$medicineId': typeof MedicinesMedicineIdRoute
  '/medicines/': typeof MedicinesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/assistant'
    | '/auth'
    | '/dashboard'
    | '/interactions'
    | '/lab-reports'
    | '/prescription'
    | '/professional'
    | '/profile'
    | '/reminders'
    | '/safety'
    | '/medicines/$medicineId'
    | '/medicines/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/assistant'
    | '/auth'
    | '/dashboard'
    | '/interactions'
    | '/lab-reports'
    | '/prescription'
    | '/professional'
    | '/profile'
    | '/reminders'
    | '/safety'
    | '/medicines/$medicineId'
    | '/medicines'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/assistant'
    | '/auth'
    | '/dashboard'
    | '/interactions'
    | '/lab-reports'
    | '/prescription'
    | '/professional'
    | '/profile'
    | '/reminders'
    | '/safety'
    | '/medicines/$medicineId'
    | '/medicines/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  AssistantRoute: typeof AssistantRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  InteractionsRoute: typeof InteractionsRoute
  LabReportsRoute: typeof LabReportsRoute
  PrescriptionRoute: typeof PrescriptionRoute
  ProfessionalRoute: typeof ProfessionalRoute
  ProfileRoute: typeof ProfileRoute
  RemindersRoute: typeof RemindersRoute
  SafetyRoute: typeof SafetyRoute
  MedicinesMedicineIdRoute: typeof MedicinesMedicineIdRoute
  MedicinesIndexRoute: typeof MedicinesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interactions': {
      id: '/interactions'
      path: '/interactions'
      fullPath: '/interactions'
      preLoaderRoute: typeof InteractionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab-reports': {
      id: '/lab-reports'
      path: '/lab-reports'
      fullPath: '/lab-reports'
      preLoaderRoute: typeof LabReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prescription': {
      id: '/prescription'
      path: '/prescription'
      fullPath: '/prescription'
      preLoaderRoute: typeof PrescriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/professional': {
      id: '/professional'
      path: '/professional'
      fullPath: '/professional'
      preLoaderRoute: typeof ProfessionalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reminders': {
      id: '/reminders'
      path: '/reminders'
      fullPath: '/reminders'
      preLoaderRoute: typeof RemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safety': {
      id: '/safety'
      path: '/safety'
      fullPath: '/safety'
      preLoaderRoute: typeof SafetyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medicines/': {
      id: '/medicines/'
      path: '/medicines'
      fullPath: '/medicines/'
      preLoaderRoute: typeof MedicinesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medicines/$medicineId': {
      id: '/medicines/$medicineId'
      path: '/medicines/$medicineId'
      fullPath: '/medicines/$medicineId'
      preLoaderRoute: typeof MedicinesMedicineIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  AssistantRoute: AssistantRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  InteractionsRoute: InteractionsRoute,
  LabReportsRoute: LabReportsRoute,
  PrescriptionRoute: PrescriptionRoute,
  ProfessionalRoute: ProfessionalRoute,
  ProfileRoute: ProfileRoute,
  RemindersRoute: RemindersRoute,
  SafetyRoute: SafetyRoute,
  MedicinesMedicineIdRoute: MedicinesMedicineIdRoute,
  MedicinesIndexRoute: MedicinesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
